from __future__ import annotations

import base64
import secrets  

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from crypto_toolkit.core.constants import AES_NONCE_SIZE, ENVELOPE_VERSION
from crypto_toolkit.core.exceptions import DecryptionError, EncryptionError
from crypto_toolkit.core.kdf import derive_key_argon2, derive_key_pbkdf2

_PBE_MAGIC = b"CTK-PBE"
_KDF_ARGON2 = b"\x01"
_KDF_PBKDF2 = b"\x02"
_SALT_LEN = 16

def password_encrypt(
    plaintext: bytes,
    password: str,
    *,
    use_argon2: bool = True,
) -> str:
    """Encrypt bytes with a password using Argon2id or PBKDF2 + AES-256-GCM."""
    try:
        if use_argon2:
            derived = derive_key_argon2(password)
            kdf_tag = _KDF_ARGON2
        else:
            derived = derive_key_pbkdf2(password)
            kdf_tag = _KDF_PBKDF2
        nonce = secrets.token_bytes(AES_NONCE_SIZE)
        ciphertext = AESGCM(derived.key).encrypt(nonce, plaintext, None)
        envelope = (
            _PBE_MAGIC
            + ENVELOPE_VERSION
            + kdf_tag
            + derived.salt
            + nonce
            + ciphertext
        )
        return base64.urlsafe_b64encode(envelope).decode()
    except Exception as exc:
        raise EncryptionError("Encryption with password failed.") from exc

def password_decrypt(token: str, password: str) -> bytes:
    """Decrypt a token generated by password_encrypt()."""
    try:
        raw = base64.urlsafe_b64decode(token.encode())
        magic_len = len(_PBE_MAGIC)

        if raw[:magic_len] != _PBE_MAGIC:
            raise DecryptionError("The envelope format is not recognized.")
        if raw[magic_len : magic_len + 1] != ENVELOPE_VERSION:
            raise DecryptionError("The envelope version is not supported.")

        kdf_tag = raw[magic_len + 1 : magic_len + 2]
        salt = raw[magic_len + 2 : magic_len + 2 + _SALT_LEN]
        rest = raw[magic_len + 2 + _SALT_LEN :]
        nonce, ciphertext = rest[:AES_NONCE_SIZE], rest[AES_NONCE_SIZE:]

        if kdf_tag == _KDF_ARGON2:
            derived = derive_key_argon2(password, salt=salt)
        elif kdf_tag == _KDF_PBKDF2:
            derived = derive_key_pbkdf2(password, salt=salt)
        else:
            raise DecryptionError("The KDF tag is not recognized within the envelope.")

        return AESGCM(derived.key).decrypt(nonce, ciphertext, None)
    except DecryptionError:
        raise
    except Exception as exc:
        raise DecryptionError(
            "Password-based decryption failed — incorrect password or corrupted data."
        ) from exc